function [fitresult, gof] = createFit(asdfg, asdf)
%CREATEFIT(ASDFG,ASDF)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : asdfg
%      Y Output: asdf
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Mar-2021 16:51:01


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( asdfg, asdf );

% Set up fittype and options.
ft = fittype( 'fourier8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.0628318530717959];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'asdf vs. asdfg', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel asdfg
ylabel asdf
grid on


