function [LoadCell,xo1,yo,zo,xrot,yrot,zrot,xlin,ylin,zlin,xmag,ymag,zmag,xa1,ya1,za1,xa2,ya2,za2] = importLoadStickData(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [LOADCELL,XO1,YO,ZO,XROT,YROT,ZROT,XLIN,YLIN,ZLIN,XMAG,YMAG,ZMAG,XA1,YA1,ZA1,XA2,YA2,ZA2]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [LOADCELL,XO1,YO,ZO,XROT,YROT,ZROT,XLIN,YLIN,ZLIN,XMAG,YMAG,ZMAG,XA1,YA1,ZA1,XA2,YA2,ZA2]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [LoadCell,xo1,yo,zo,xrot,yrot,zrot,xlin,ylin,zlin,xmag,ymag,zmag,xa1,ya1,za1,xa2,ya2,za2] = importfile('wingsOnGoodRunA.txt',1, 1844);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2021/04/12 16:47:19

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
LoadCell = cell2mat(raw(:, 1));
xo1 = cell2mat(raw(:, 2));
yo = cell2mat(raw(:, 3));
zo = cell2mat(raw(:, 4));
xrot = cell2mat(raw(:, 5));
yrot = cell2mat(raw(:, 6));
zrot = cell2mat(raw(:, 7));
xlin = cell2mat(raw(:, 8));
ylin = cell2mat(raw(:, 9));
zlin = cell2mat(raw(:, 10));
xmag = cell2mat(raw(:, 11));
ymag = cell2mat(raw(:, 12));
zmag = cell2mat(raw(:, 13));
xa1 = cell2mat(raw(:, 14));
ya1 = cell2mat(raw(:, 15));
za1 = cell2mat(raw(:, 16));
xa2 = cell2mat(raw(:, 17));
ya2 = cell2mat(raw(:, 18));
za2 = cell2mat(raw(:, 19));


